FROM jenkins/jenkins:lts-jdk17
COPY plugins.txt /plugins.txt
RUN jenkins-plugin-cli --plugin-file /plugins.txt
COPY jenkins.yaml /jenkins.yaml
ENV CASC_JENKINS_CONFIG="/jenkins.yaml"
# bind mount instead
#COPY jenkins.yaml /jenkins.yaml
# ENV CASC_JENKINS_CONFIG="/git/jeknins-opinionated/jenkins.yaml"
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false -Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
