FROM jenkins/jenkins:lts-jdk17
COPY plugins.txt /plugins.txt
RUN jenkins-plugin-cli --plugin-file /plugins.txt
COPY jenkins.yaml /jenkins.yaml
USER root
RUN apt-get update && apt-get install -y make
USER jenkins
ENV CASC_JENKINS_CONFIG="/jenkins.yaml"
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false \
-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true \
-Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true"
ENV GIT_AUTHOR_NAME=jenkins
ENV GIT_AUTHOR_EMAIL=jenkins@opinionated
ENV GIT_COMMITTER_NAME=jenkins
ENV GIT_COMMITTER_EMAIL=jenkins@opinionated
